### Predict from input data
POST http://localhost:8080/invocations
Content-Type: application/json

{
  "dataframe_split": {
    "columns": [
      "fixed acidity",
      "volatile acidity",
      "citric acid",
      "residual sugar",
      "chlorides",
      "free sulfur dioxide",
      "total sulfur dioxide",
      "density",
      "pH",
      "sulphates",
      "alcohol"
    ],
    "data": [[7, 0.27, 0.36, 20.7, 0.045, 45, 170, 1.001, 3, 0.45, 8.8]]
  }
}

### Search experiments
POST http://localhost:8080/api/2.0/mlflow/experiments/search
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
  "max_results": 100
}

### Search runs in experiment
POST http://localhost:8080/api/2.0/mlflow/runs/search
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
  "experiment_ids": ["983535187500980374"]
}
