[tool.poetry]
name = "mlflow-sample"
version = "0.1.0"
description = ""
authors = ["Mitsuru Takeda <m.t.hagaren1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mlflow = "^2.16.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
